### PR TITLE
Improvement: enable changing the aspect at runtime

### LINKED ISSUE #7: changing aspect state has no effect
open the demo page and change the aspect state using the react dev tools

the cropper should update its gutter according to the new aspect ratio, but it does not, the gutter does not change.

### PR DESCRIPTION
**Pull request by ValentinH**
Close #7

### CODE REVIEW

**Comment by ValentinH** [comment]
@mbretter please let me know if it matches what you expect?

Updated sandbox:  https://codesandbox.io/s/l5r270r19q

**Comment by mbretter** [comment]
hmm, the demo still changes the zoom, not the aspect ...

**Comment by ValentinH** [comment]
I forgot to save (thought it was auto-saved). Should be better now 🙂

**Comment by mbretter** [comment]
très bien, merci

**Comment by ValentinH** [comment]
Released at 1.2.0: https://github.com/ricardo-ch/react-easy-crop/releases/tag/v1.2.0

**Pull request merged**
