### PR TITLE
add onError prop to Img

### PR DESCRIPTION
**Pull request by bexoss**
add onError prop to Img

### CODE REVIEW

**Comment by bexoss** [comment]
@ValentinH Oh, I forgot `props.`, Could you add the onError handler for ``?  
I want to use fallback image if the src not exist.

**Comment by ValentinH** [comment]
This looks good to me, just before merging, could you add this to the documentation?

**Comment by bexoss** [comment]
Okay, I added pull request. Should I used same branch? Actually I don't have enough experiences to pull request to other project. So it little confused me. Anyway I added pull request if you find any wrong please edit it correctly :) I want to push commit to this same branch but I found the documentation updated few hours ago so I created new one to new docs. I don't know git handle it automatically or not :(

**Comment by ValentinH** [comment]
Indeed, you should have done it in the same PR. But let's merge both :)

**Comment by ValentinH** [comment]
Released as 1.6: https://github.com/ricardo-ch/react-easy-crop/releases/tag/v1.6.0

**Pull request merged**
